# Generated by Django 6.1 on 2026-09-14 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProblemStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempts', models.IntegerField(default=0)),
                ('solved', models.BooleanField(default=False)),
                ('last_attempted_at', models.DateTimeField(blank=True, null=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_stats', to='problems.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Статистика юзера по задаче',
                'verbose_name_plural': 'Статистика юзеров по задачам',
                'indexes': [models.Index(fields=['user', 'solved', 'last_attempted_at'], name='profiles_us_user_id_eb0f9a_idx')],
                'unique_together': {('user', 'problem')},
            },
        ),
    ]
