# Generated by Django 6.1 on 2026-09-15 08:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_userproblemstats'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=24)),
                ('name', models.CharField(max_length=24)),
                ('color', models.CharField(default='#ffffff', max_length=7)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('icon', models.URLField(blank=True)),
                ('is_assignable', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'badge',
                'verbose_name_plural': 'badges',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='userproblemstats',
            options={'verbose_name': 'User statistics for the task', 'verbose_name_plural': 'User statistics by task'},
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='profiles.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User badge',
                'verbose_name_plural': 'Users Badges',
                'unique_together': {('user', 'badge')},
            },
        ),
    ]
