# Generated by Django 6.1 on 2026-09-14 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problems', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('waiting', 'Ожидание'), ('in_progress', 'В процессе'), ('finished', 'Завершён')], default='waiting', max_length=20, verbose_name='Статус')),
                ('mode', models.CharField(choices=[('ranked', 'Рейтинговый'), ('training', 'Тренировочный')], default='ranked', max_length=20, verbose_name='Режим')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Начало')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Конец')),
                ('duration_ms', models.IntegerField(blank=True, null=True, verbose_name='Длительность (мс)')),
                ('end_reason', models.CharField(blank=True, choices=[('solved', 'Решено'), ('timeout', 'Таймаут'), ('disconnect', 'Отключение'), ('surrender', 'Сдача')], max_length=20, null=True, verbose_name='Причина завершения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matches', to='problems.problem', verbose_name='Задача')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_matches', to=settings.AUTH_USER_MODEL, verbose_name='Победитель')),
            ],
            options={
                'verbose_name': 'Матч',
                'verbose_name_plural': 'Матчи',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MatchPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=20, verbose_name='Язык')),
                ('elo_before', models.IntegerField(verbose_name='Эло до')),
                ('elo_after', models.IntegerField(blank=True, null=True, verbose_name='Эло после')),
                ('elo_delta', models.IntegerField(blank=True, null=True, verbose_name='Изменение Эло')),
                ('tests_passed', models.IntegerField(default=0, verbose_name='Пройдено тестов')),
                ('tests_total', models.IntegerField(default=0, verbose_name='Всего тестов')),
                ('solved_at', models.DateTimeField(blank=True, null=True, verbose_name='Решено в')),
                ('result', models.CharField(blank=True, choices=[('win', 'Победа'), ('loss', 'Поражение'), ('draw', 'Ничья')], max_length=20, null=True, verbose_name='Результат')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='matches.match', verbose_name='Матч')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_players', to=settings.AUTH_USER_MODEL, verbose_name='Игрок')),
            ],
            options={
                'verbose_name': 'Игрок матча',
                'verbose_name_plural': 'Игроки матчей',
                'unique_together': {('match', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=20, verbose_name='Язык')),
                ('code', models.TextField(verbose_name='Код')),
                ('verdict', models.CharField(choices=[('accepted', 'Принято'), ('wrong_answer', 'Неверный ответ'), ('time_limit', 'Превышено время'), ('memory_limit', 'Превышена память'), ('runtime_error', 'Ошибка выполнения'), ('compilation_error', 'Ошибка компиляции')], max_length=30, verbose_name='Вердикт')),
                ('tests_passed', models.IntegerField(default=0, verbose_name='Пройдено тестов')),
                ('tests_total', models.IntegerField(default=0, verbose_name='Всего тестов')),
                ('runtime_ms', models.IntegerField(blank=True, null=True, verbose_name='Время выполнения (мс)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='matches.match', verbose_name='Матч')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL, verbose_name='Игрок')),
            ],
            options={
                'verbose_name': 'Сабмит',
                'verbose_name_plural': 'Сабмиты',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['match', 'user'], name='matches_sub_match_i_059ec7_idx')],
            },
        ),
    ]
