# Generated by Django 6.1 on 2026-09-14 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
        ('problems', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['-created_at'], 'verbose_name': 'Match', 'verbose_name_plural': 'Matches'},
        ),
        migrations.AlterModelOptions(
            name='matchplayer',
            options={'verbose_name': 'Player of match', 'verbose_name_plural': 'Players of match'},
        ),
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ['-created_at'], 'verbose_name': 'Submit', 'verbose_name_plural': 'Submits'},
        ),
        migrations.AlterField(
            model_name='match',
            name='end_reason',
            field=models.CharField(blank=True, choices=[('solved', 'Solved'), ('timeout', 'Timeout'), ('disconnect', 'Disconnect'), ('surrender', 'Surrender')], max_length=20, null=True, verbose_name='Reason for completion'),
        ),
        migrations.AlterField(
            model_name='match',
            name='mode',
            field=models.CharField(choices=[('ranked', 'Ranked'), ('training', 'Training')], default='ranked', max_length=20, verbose_name='Mode'),
        ),
        migrations.AlterField(
            model_name='match',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matches', to='problems.problem', verbose_name='Task'),
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('in_progress', 'In_progress'), ('finished', 'Finished')], default='waiting', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_matches', to=settings.AUTH_USER_MODEL, verbose_name='Winner'),
        ),
        migrations.AlterField(
            model_name='matchplayer',
            name='elo_after',
            field=models.IntegerField(blank=True, null=True, verbose_name='Elo after'),
        ),
        migrations.AlterField(
            model_name='matchplayer',
            name='elo_before',
            field=models.IntegerField(verbose_name='Elo Before'),
        ),
        migrations.AlterField(
            model_name='matchplayer',
            name='elo_delta',
            field=models.IntegerField(blank=True, null=True, verbose_name='Rating changed'),
        ),
        migrations.AlterField(
            model_name='matchplayer',
            name='language',
            field=models.CharField(max_length=20, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='matchplayer',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='matches.match', verbose_name='Match'),
        ),
        migrations.AlterField(
            model_name='matchplayer',
            name='result',
            field=models.CharField(blank=True, choices=[('win', 'Win'), ('loss', 'Lose'), ('draw', 'Draw')], max_length=20, null=True, verbose_name='Result'),
        ),
        migrations.AlterField(
            model_name='matchplayer',
            name='solved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Solved at'),
        ),
        migrations.AlterField(
            model_name='matchplayer',
            name='tests_passed',
            field=models.IntegerField(default=0, verbose_name='Tests passed'),
        ),
        migrations.AlterField(
            model_name='matchplayer',
            name='tests_total',
            field=models.IntegerField(default=0, verbose_name='All tests'),
        ),
        migrations.AlterField(
            model_name='matchplayer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_players', to=settings.AUTH_USER_MODEL, verbose_name='Player'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='code',
            field=models.TextField(verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='language',
            field=models.CharField(max_length=20, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='matches.match', verbose_name='Match'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='runtime_ms',
            field=models.IntegerField(blank=True, null=True, verbose_name='lead time (мс)'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='tests_passed',
            field=models.IntegerField(default=0, verbose_name='Tests passed'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='tests_total',
            field=models.IntegerField(default=0, verbose_name='All tests'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL, verbose_name='Player'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='verdict',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('wrong_answer', 'Wrong answer'), ('time_limit', 'Time limit'), ('memory_limit', 'Memory limit'), ('runtime_error', 'Runtime error'), ('compilation_error', 'Compilation error')], max_length=30, verbose_name='Verdict'),
        ),
    ]
